export const LANGUAGES = [
  { langId: 1, name: 'Arabic', arName: 'العربية' },
  { langId: 2, name: 'English', arName: 'الإنجليزية' },
  { langId: 3, name: 'Mandarin Chinese', arName: 'الصينية الماندارين' },
  { langId: 4, name: 'German', arName: 'الألمانية' },
  { langId: 5, name: 'French', arName: 'الفرنسية' },
  { langId: 6, name: 'Spanish', arName: 'الإسبانية' },
  { langId: 7, name: 'Turkish', arName: 'التركية' },
  { langId: 8, name: 'Italian', arName: 'الإيطالية' },
  { langId: 9, name: 'Hindi', arName: 'الهندية' },
  { langId: 10, name: 'Russian', arName: 'الروسية' },
  { langId: 11, name: 'Bengali', arName: 'البنغالية' },
  { langId: 12, name: 'Portuguese', arName: 'البرتغالية' },
  { langId: 13, name: 'Japanese', arName: 'اليابانية' },
  { langId: 14, name: 'Urdu', arName: 'الأردية' },
  { langId: 15, name: 'Korean', arName: 'الكورية' },
  { langId: 16, name: 'Tamil', arName: 'التاميل' },
  { langId: 17, name: 'Punjabi', arName: 'البنجابية' },
  { langId: 18, name: 'Marathi', arName: 'الماراثى' },
  { langId: 19, name: 'Telugu', arName: 'التيلجو' },
  { langId: 20, name: 'Wu Chinese', arName: 'اللغة الصينية وو' },
  { langId: 21, name: 'Vietnamese', arName: 'الفيتنامية' },
  { langId: 22, name: 'Cantonese Chinese', arName: 'الصينية الكانتونية' },
  { langId: 23, name: 'Filipino', arName: 'الفلبينية' },
  { langId: 24, name: 'Swahili', arName: 'السواحيلية' },
  { langId: 25, name: 'Javanese', arName: 'الجاوية' },
  { langId: 26, name: 'Gujarati', arName: 'الغوجاراتية' },
  { langId: 27, name: 'Polish', arName: 'البولندية' },
  { langId: 28, name: 'Ukrainian', arName: 'الأوكرانية' },
  { langId: 29, name: 'Malayalam', arName: 'الماليالامية' },
  { langId: 30, name: 'Kannada', arName: 'الكانادا' },
  { langId: 31, name: 'Odia', arName: 'الأوريا' },
  { langId: 32, name: 'Burmese', arName: 'البورمية' },
  { langId: 33, name: 'Sundanese', arName: 'السوندانية' },
  { langId: 34, name: 'Thai', arName: 'التايلاندية' },
  { langId: 35, name: 'Sindhi', arName: 'السندية' },
  { langId: 36, name: 'Uzbek', arName: 'الأوزبكية' },
  { langId: 37, name: 'Amharic', arName: 'الأمهرية' },
  { langId: 38, name: 'Fula', arName: 'الفولانية' },
  { langId: 39, name: 'Romanian', arName: 'الرومانية' },
  { langId: 40, name: 'Dutch', arName: 'الهولندية' },
  { langId: 41, name: 'Serbo-Croatian', arName: 'الصربية-الكرواتية' },
  { langId: 42, name: 'Nepali', arName: 'النيبالية' },
  { langId: 43, name: 'Greek', arName: 'اليونانية' },
  { langId: 44, name: 'Chittagonian', arName: 'التشيتاغونيان' },
  { langId: 45, name: 'Kazakh', arName: 'الكازاخستانية' },
  { langId: 46, name: 'Deccan', arName: 'الدكن' },
  { langId: 47, name: 'Hungarian', arName: 'الهنغارية' },
  { langId: 48, name: 'Kinyarwanda', arName: 'الكينيارواندا' },
  { langId: 49, name: 'Zulu', arName: 'الزولو' },
  { langId: 50, name: 'South Azerbaijani', arName: 'الأذربيجانية الجنوبية' },
  { langId: 51, name: 'Czech', arName: 'التشيكية' },
  { langId: 52, name: 'Kinyarwanda', arName: 'الكينيارواندا' },
  { langId: 53, name: 'Min Bei Chinese', arName: 'الصينية مين بي' },
  { langId: 54, name: 'Sylheti', arName: 'السيلهيتي' },
  { langId: 55, name: 'Quechua', arName: 'الكتشوا' },
];
