export const NATIONALITIES = {
  EG: { EN: 'Egyptian', AR: 'مصري' },
  SA: { EN: 'Saudi Arabian', AR: 'سعودي' },
  CN: { EN: 'Chinese', AR: 'صيني' },
  AE: { EN: 'Emirati', AR: 'إماراتي' },
  US: { EN: 'American', AR: 'أمريكي' },
  CA: { EN: 'Canadian', AR: 'كندي' },
  FR: { EN: 'French', AR: 'فرنسي' },
  DE: { EN: 'German', AR: 'ألماني' },
  IT: { EN: 'Italian', AR: 'إيطالي' },
  JP: { EN: 'Japanese', AR: 'ياباني' },
  KR: { EN: 'Korean', AR: 'كوري' },
  BR: { EN: 'Brazilian', AR: 'برازيلي' },
  ES: { EN: 'Spanish', AR: 'إسباني' },
  PT: { EN: 'Portuguese', AR: 'برتغالي' },
  RU: { EN: 'Russian', AR: 'روسي' },
  IN: { EN: 'Indian', AR: 'هندي' },
  PK: { EN: 'Pakistani', AR: 'باكستاني' },
  NG: { EN: 'Nigerian', AR: 'نيجيري' },
  ZA: { EN: 'South African', AR: 'جنوب أفريقي' },
  KE: { EN: 'Kenyan', AR: 'كيني' },
  ET: { EN: 'Ethiopian', AR: 'إثيوبي' },
  AU: { EN: 'Australian', AR: 'أسترالي' },
  NZ: { EN: 'New Zealander', AR: 'نيوزيلندي' },
  ID: { EN: 'Indonesian', AR: 'إندونيسي' },
  TH: { EN: 'Thai', AR: 'تايلندي' },
  VN: { EN: 'Vietnamese', AR: 'فيتنامي' },
  PH: { EN: 'Filipino', AR: 'فلبيني' },
  MX: { EN: 'Mexican', AR: 'مكسيكي' },
  AR: { EN: 'Argentinian', AR: 'أرجنتيني' },
  CL: { EN: 'Chilean', AR: 'تشيلي' },
  CO: { EN: 'Colombian', AR: 'كولومبي' },
  PE: { EN: 'Peruvian', AR: 'بيروفي' },
  GB: { EN: 'British', AR: 'بريطاني' },
  GR: { EN: 'Greek', AR: 'يوناني' },
  TR: { EN: 'Turkish', AR: 'تركي' },
  IR: { EN: 'Iranian', AR: 'إيراني' },
  IQ: { EN: 'Iraqi', AR: 'عراقي' },
  SY: { EN: 'Syrian', AR: 'سوري' },
  JO: { EN: 'Jordanian', AR: 'أردني' },
  LB: { EN: 'Lebanese', AR: 'لبناني' },
  TN: { EN: 'Tunisian', AR: 'تونسي' },
  MA: { EN: 'Moroccan', AR: 'مغربي' },
  DZ: { EN: 'Algerian', AR: 'جزائري' },
  SD: { EN: 'Sudanese', AR: 'سوداني' },
  ZW: { EN: 'Zimbabwean', AR: 'زيمبابوي' },
  GH: { EN: 'Ghanaian', AR: 'غاني' },
  CI: { EN: 'Ivorian', AR: 'إيفواري' },
  LR: { EN: 'Liberian', AR: 'ليبيري' },
  UG: { EN: 'Ugandan', AR: 'أوغندي' },
};
