export enum SmsMessageEnum {
  HELLO_MESSAGE = 'HELLO_MESSAGE',
  PHONE_VERIFICATION_CODE = 'PHONE_VERIFICATION_CODE',
  RESET_PASSWORD_CODE = 'RESET_PASSWORD_CODE',
  LOGIN_VERIFICATION_CODE = 'LOGIN_VERIFICATION_CODE',
  UPDATE_PHONE_NUMBER = 'UPDATE_PHONE_NUMBER',
}
